export const columns = [
    "name",
    "category",
    "amount",
    "calories",
    "carbs",
    "fat",
    "protein",
];

export const mcData = [
    {
        name: "Bacon Roll",
        category: ["breakfast", "pork"],
        amount: "1 roll",
        calories: 351,
        carbs: 40,
        fat: 11,
        protein: 22,
        id: 1,
    },
    {
        name: "Sausage & Egg Mcmuffin",
        category: ["breakfast", "pork"],
        amount: "1 roll",
        calories: 430,
        carbs: 27,
        fat: 24,
        protein: 26,
        id: 2,
    },
    {
        name: "French Fries - Large Portion",
        category: ["sides", "vegetarian"],
        amount: "1 lrg portion",
        calories: 460,
        carbs: 60,
        fat: 23,
        protein: 5,
        id: 3,
    },
    {
        name: "Hash Brown",
        category: ["sides", "vegetarian"],
        amount: "1 hash brown",
        calories: 127,
        carbs: 14,
        fat: 7,
        protein: 1,
        id: 4,
    },
    {
        name: "20 Chicken Nuggets Share Box",
        category: ["chicken"],
        amount: "20 Nuggets",
        calories: 863,
        carbs: 61,
        fat: 45,
        protein: 53,
        id: 5,
    },
    {
        name: "Potato Wedges",
        category: ["sides", "vegetarian"],
        amount: "1 serving",
        calories: 345,
        carbs: 44,
        fat: 15,
        protein: 5,
        id: 6,
    },
    {
        name: "Chicken Sandwich",
        category: ["chicken", "burger"],
        amount: "1 serving",
        calories: 333,
        carbs: 44,
        fat: 16,
        protein: 17,
        id: 7,
    },
    {
        name: "Double Cheeseburger ",
        category: ["beef", "burger"],
        amount: "1 burger",
        calories: 440,
        carbs: 32,
        fat: 23,
        protein: 26,
        id: 8,
    },
    {
        name: "Chocolatey Donut",
        category: ["dessert"],
        amount: "1 donut",
        calories: 254,
        carbs: 28,
        fat: 13,
        protein: 5,
        id: 9,
    },
    {
        name: "Chicken Legend",
        category: ["chicken", "burger"],
        amount: "1 burger",
        calories: 459,
        carbs: 55,
        fat: 14,
        protein: 27,
        id: 10,
    },
];
